// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

   static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgtECn-SAasgjde2HSFIa4x2J52TuRDAY',
    appId: '1:1073736183358:web:0f75793871a99724c1eb6f',
    messagingSenderId: '1073736183358',
    projectId: 'ecosmart-app-new',
    authDomain: 'ecosmart-app-new.firebaseapp.com',
    storageBucket: 'ecosmart-app-new.firebasestorage.app',
    measurementId: 'G-1WZXF32CYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2xxcdIuLaLWbtC9bGC4Wu1O9c-Q6IqVY',
    appId: '1:1073736183358:android:9fdb124fedc4286fc1eb6f',
    messagingSenderId: '1073736183358',
    projectId: 'ecosmart-app-new',
    storageBucket: 'ecosmart-app-new.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2XHheDLL9Q1Bat2jjAPaBmqTDhRY5P20',
    appId: '1:1073736183358:ios:9d794ca73390833ec1eb6f',
    messagingSenderId: '1073736183358',
    projectId: 'ecosmart-app-new',
    storageBucket: 'ecosmart-app-new.firebasestorage.app',
    iosBundleId: 'com.example.ecosmartApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2XHheDLL9Q1Bat2jjAPaBmqTDhRY5P20',
    appId: '1:1073736183358:ios:9d794ca73390833ec1eb6f',
    messagingSenderId: '1073736183358',
    projectId: 'ecosmart-app-new',
    storageBucket: 'ecosmart-app-new.firebasestorage.app',
    iosBundleId: 'com.example.ecosmartApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgtECn-SAasgjde2HSFIa4x2J52TuRDAY',
    appId: '1:1073736183358:web:d08e53471ad25958c1eb6f',
    messagingSenderId: '1073736183358',
    projectId: 'ecosmart-app-new',
    authDomain: 'ecosmart-app-new.firebaseapp.com',
    storageBucket: 'ecosmart-app-new.firebasestorage.app',
    measurementId: 'G-QFY7DP5KGX',
  );
}
